/*
 * Full-Stack project API
 *
 * This is a Tabletop Website Server based on my Fullstack course [project](https://github.com/ArtemVasilevMIPT/FullstackProject/tree/master)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (import (
	"time"
	"os"
)

)

type Game struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	DateCreated time.Time `json:"date_created,omitempty"`

	Desciption string `json:"desciption,omitempty"`

	State string `json:"state,omitempty"`

	Players []int64 `json:"players,omitempty"`

	Image **os.File `json:"image,omitempty"`

	Gm int64 `json:"gm,omitempty"`
}
