/*
 * Full-Stack project API
 *
 * This is a Tabletop Website Server based on my Fullstack course [project](https://github.com/ArtemVasilevMIPT/FullstackProject/tree/master)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserCreateBody struct {

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	Nickname string `json:"nickname,omitempty"`
}
