/*
 * Full-Stack project API
 *
 * This is a Tabletop Website Server based on my Fullstack course [project](https://github.com/ArtemVasilevMIPT/FullstackProject/tree/master)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	GameList []Game `json:"game_list,omitempty"`
}
