/*
 * Full-Stack project API
 *
 * This is a Tabletop Website Server based on my Fullstack course [project](https://github.com/ArtemVasilevMIPT/FullstackProject/tree/master)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
	"os"
)

type User struct {
	Id int64 `json:"id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Email string `json:"email,omitempty"`
	DateJoined time.Time `json:"date_joined,omitempty"`
	Password string `json:"password,omitempty"`
	ProfilePic **os.File `json:"profile_pic,omitempty"`
}
